image: s0kil/microverse-gitpod

ports:
  # VNC
  - port: 6080
    onOpen: open-browser
  # Chrome Services
  - port: 9514
    onOpen: ignore
  - port: 9515
    onOpen: ignore

vscode:
  extensions:
    - rebornix.ruby@0.27.0:QyGBeRyslOfdRgOPRGm6PQ==
    - castwide.solargraph@0.22.0:gbvTA8wx5YQV2KluDIFp0w==
    - wingrunr21.vscode-ruby@0.27.0:beIqQUhLRuJ5Vao4B2Lyng==
    - connorshea.vscode-ruby-test-adapter@0.7.1:2whJIQLBlwxM0+/BSzDWYw==
    - bung87.rails@0.16.7:IXQaE7PUhn9K+2iTc/HF1w==
    - karunamurti.haml@1.3.1:EDy7DPmRjp+lAkYNmcAmLA==
    - sianglim.slim@0.1.1:NQFS+52G0SH0/fp66K9i6g==
    - samuelcolvin.jinjahtml@0.15.0:DAGgO4M/cnuxqBhFQ/C/Gw==
    - formulahendry.auto-close-tag@0.5.8:E3l7NRdQytF0+ykejfHKdQ==
    - runem.lit-plugin@1.2.1:llHUlx8TJ6tFKGa1t6dpLQ==
    - Zignd.html-css-class-completion@1.19.0:Soyzg8syqQX3vm86CKnPtg==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - ecmel.vscode-html-css@0.2.3:hh8R73s3n0g/eQ8EL9PatQ==
    - vscode.html-language-features@1.49.3:exs337K13A8Oe3dryi2ZEQ==
    - pucelle.vscode-css-navigation@1.9.0:YZf2Ujfn381OEY/pYQikew==
    - bradlc.vscode-tailwindcss@0.4.3:OmgUwJW/nFom0SHcYT4VnQ==
    - stylelint.vscode-stylelint@0.84.0:9CBp08IKCKrtFWDGzEgyjQ==
    - vscode.css-language-features@1.49.3:nBcGM2IyrYtPpczOUCFaoQ==
    - gencer.html-slim-scss-css-class-completion@1.7.7:IQJ5yzbxHud/K25s5zXOUw==
    - vscode.json-language-features@1.49.3:sjA7NJrsY5IIBZwEplr5uw==
    - vscode.docker@1.49.3:u8ak975skeaO3/SHKX0wsw==
    - ms-vscode.js-debug@1.50.0:9GlGCUPeE17EVVLGPTABIg==
    - HansUXdev.javascript-first-snippets@0.0.5:PqRpccw5mn10agYrz6/Wrw==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - dsznajder.es7-react-js-snippets@3.0.0:9YEGn/57fW8lJt7cVxJQDQ==
    - christian-kohler.path-intellisense@2.3.0:4aNBD+QUimscVO5NwoATiw==
    - ionutvmi.path-autocomplete@1.14.0:v849GEbOhxBaEuspHxe8SQ==
    - syler.sass-indented@1.8.12:p+MmW74V1Fvj6+I5xXlUcA==
    - SonarSource.sonarlint-vscode@1.17.0:ykgEHpHsIPlCEJ+/QYVcrw==
    - vincaslt.highlight-matching-tag@0.9.9:vzmHwY/WukBrdwbHugD6SQ==
    - svelte.svelte-vscode@102.1.1:uSx6lY6QVmt3AsWibDEyxg==
    - fivethree.vscode-svelte-snippets@0.5.0:rRkcaFrMb8wbTuH6kbGEQQ==
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
    - octref.vetur@0.28.0:bW1RGNnmWYQO43JdJgK34w==
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - PKief.material-icon-theme@4.3.0:URe4ANXBLYHzB6CeGyTN8A==
    - formulahendry.code-runner@0.11.0:HNAnyDKL6fUn1G8QfbKLpQ==
    - vscode.git@1.49.3:h7eabJkE7MJAL/dgN28nkg==
    - vscode.git-ui@1.49.3:8zXGkpIoxU8uDxQARdkKAg==
    - vector-of-bool.gitflow@1.2.1:xjPKO1kQGbSQBAHVYAZG9g==
    - KnisterPeter.vscode-github@0.30.4:2VfqCD2ylXzrXT7Lc5iN3Q==
    - aliariff.vscode-erb-beautify@0.2.0:q+zrJTVKf5jjU0o9PupRjQ==
    - bung87.vscode-gemfile@0.4.1:jYT6FRuH8C+Y+pBqaSL8BA==
    - hbenl.vscode-test-explorer@2.19.2:8rKHUShFJJd0UivektEkng==
